Replace imports from sage.all
3-manifolds/SnapPy pull request #123
Opened 2024-10-29 23:10 UTC by mkoeppe

Preparation for using modularized distributions of the Sage library.

Done using `sage -fiximports`.

2024-10-31 07:26 UTC, unhyperbolic commented
How stable are these import paths? How many versions of sage do they go back?

In the past, we had large try: ...  except ImportError: ... blocks to account for different sage versions.

2024-10-31 08:10 UTC, mkoeppe commented
> How stable are these import paths? How many versions of sage do they go back?

AFAICS these imports are all unchanged in Sage over at least the past 5 years

> The CI is configured to run SnapPy against various docker containers with different SageMath versions. It reports that 4 out of 11 suites failed. Unfortunately, github doesn't let me see which :(

Are you saying that the current branch was already tested? 

By the way, my motivation here is to get SnapPy to run on top of my modularized fork of Sage https://github.com/passagemath/passagemath

2024-10-31 16:03 UTC, NathanDunfield commented
Our CI tests SnapPy on the official Sage Docker images, from 9.3 (circa 2021) up to 10.4.  We do not test against the development branch of Sage.

I enabled the CI for this PR and tweaker the CI config.  The PR fails when running the doctests for Sage 9.* and passes for Sage 10.*.   The common error is:
```
  File "/home/sage/sage/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/snappy/snap/polished_reps.py", line 18, in <module>
    from sage.combinat.subset import powerset
ImportError: cannot import name 'powerset' from 'sage.combinat.subset' (/home/sage/sage/local/var/lib/sage/venv-python3.9.9/lib/python3.9/site-packages/sage/combinat/subset.py)
```

2024-10-31 23:31 UTC, mkoeppe commented
Thanks @NathanDunfield. Would changes like just pushed in ada49ea5097b7f9d1cef80b0ddb9d72aeec52255 be acceptable?

2024-11-01 01:29 UTC, NathanDunfield commented
> Would changes like just pushed in [ada49ea](https://github.com/3-manifolds/SnapPy/commit/ada49ea5097b7f9d1cef80b0ddb9d72aeec52255) be acceptable?

Overall, it looks good to me.  For the frequently imported things, it might be better to do the import in `sage_helper.py `, especially if it needs a try-except block.  See the example of `ComplexField` in that file.

2024-11-01 06:48 UTC, mkoeppe commented
Here's a more complete version (still has a failure in doctesting `snappy.database` that I don't understand at the moment).
With this version, I can get `snappy.test` to run on top of only passagemath-flint, passagemath-repl, passagemath-groups,     passagemath-symbolics, passagemath-plot, passagemath-graphs.

2024-12-31 06:15 UTC, mkoeppe commented
@NathanDunfield @unhyperbolic This passes tests now

2024-12-31 14:18 UTC, NathanDunfield requested changes

2024-12-31 14:18 UTC, NathanDunfield commented on python/snap/find_field.py
Now that you've added a bunch of Sage imports to `sage_helper.py`, I think it makes sense to import those objects through it here and in analogous places throughout.  E.g.
```
from ..sage_helper import ZZ, QQ, matrix
```

2025-01-01 23:05 UTC, mkoeppe commented on python/snap/find_field.py
Done, I think. Preview: https://github.com/mkoeppe/SnapPy/actions/runs/12575148681

Happy new year!

2025-01-02 04:26 UTC, NathanDunfield commented
@mkoeppe Looks good to me so far.

@unhyperbolic and @culler any comments?

2025-01-14 07:19 UTC, unhyperbolic commented on python/sage_helper.py
> +        from sage.all import RIF, CIF
Do we actually need this?

Note: I do use the name RIF and CIF for RealIntervalField and ComplexIntervalField instances with precisions different from RealIntervalField() and ComplexIntervalField().

2025-01-14 07:23 UTC, unhyperbolic commented on python/verify/upper_halfspace/ideal_point.py
> +    from ...sage_helper import I, matrix, RIF, CIF
This RIF and CIF import should go into run_tests again.

2025-01-14 07:24 UTC, unhyperbolic commented on python/verify/upper_halfspace/finite_point.py
> +    import sage
Is this "import sage" needed?

2025-01-14 17:23 UTC, merged

2025-01-14 19:17 UTC, mkoeppe commented
Thanks for merging! I'll follow up with some more proposed changes